Data base integration
Stefan-Stev/Quotation pull request #1
Opened 2021-07-16 10:50 UTC by Stefan-Stev

Pull request ( merge request) from DataBaseIntegration  branch to main branch

2021-07-19 06:47 UTC, ursaciuc-adrian commented on QuotationsWebApi/Controllers/v1.0/DossiersController.cs
> +    public class DossiersController:BaseApiController
identation

2021-07-19 07:04 UTC, ursaciuc-adrian requested changes

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Controllers/v1.0/DossiersController.cs
> +                DossierGetDto dossierDto = new DossierGetDto();
why don't u use automapper?

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Controllers/v1.0/DossiersController.cs
> +                dossierDto.Year = dossierEntity.Year;
make use of automapper

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Controllers/v1.0/DossiersController.cs
> +            }
how do you know if this is an error because the entity does not exist or if an error occurs when connecting to the database or other type of errors?

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Controllers/v1.0/DossiersController.cs
> +            if (id != dossierDto.Id)
if you want it to be the same id why do you need an additional parameter for the id? we could use the id from the dossierDto only

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Controllers/v1.0/DossiersController.cs
> +            return NoContent();
I think it's better if you return an Ok status instead. NoContent is more for when you want to get something, you find the entity, but there is nothing in it.

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Controllers/v1.0/QuotationsController.cs
> +            return NoContent();
Ok status

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Data/Migrations/20210707140235_InitialCreate.cs
> +                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
why is this text? wouldn't it be better to be of type 'uniqueindetifier'?

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Data/Migrations/20210707140235_InitialCreate.cs
> +                    DossierId = table.Column<Guid>(type: "TEXT", nullable: false),
same for this column

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Data/Migrations/20210707140235_InitialCreate.cs
> +                    DataCreated = table.Column<DateTime>(type: "TEXT", nullable: false),
those two should be dates

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Data/Migrations/20210712145352_SecondCreate.cs
> +                    DossierId = table.Column<Guid>(type: "TEXT", nullable: false),
uniqueidentifier

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Dtos/QuotationDtos/QuotationForCreationDto.cs
> +        public DateTime DataUntilValid { get; set; }
in the database configuration, you set all fields as required, they should be required here also

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Dtos/QuotationDtos/QuotationGetDto.cs
> +        public Guid Id { get; set; }
you can add some attributes to those fields to help with the generation of the database.
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]

2021-07-19 07:04 UTC, ursaciuc-adrian commented on QuotationsWebApi/Entities/Dossier.cs
> +        public Guid Id { get; set; }
same here

2021-07-22 14:06 UTC, Stefan-Stev reviewed
where is requested change?

2021-07-28 07:55 UTC, closed without merging